name: echo
description: Lightweight XMPP client, purely written in dart.
version: 0.0.5
repository: https://github.com/vsevex/echo

environment:
  sdk: ">=3.0.2 <4.0.0"

dev_dependencies:
  test: ^1.21.0
dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  lint: ^2.1.2
  logger: ^1.3.0
  web_socket_channel: ^2.4.0
  xml: ^6.3.0
