name: echo
description: Lightweight XMPP client, purely written in dart.
version: 0.1.0
repository: https://github.com/vsevex/echo

environment:
  sdk: ">=3.0.7 <4.0.0"

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  events_emitter: ^0.5.2
  lint: ^2.1.2
  logger: ^2.0.2
  web_socket_client: ^0.1.0
  xml: ^6.3.0

dev_dependencies:
  test: ^1.21.0
