name: whixp
description: Streamline Your XMPP Messaging with Lightweight Dart-Based XMPP Client
version: 2.0.0-beta1
repository: https://github.com/vsevex/whixp
issue_tracker: https://github.com/vsevex/whixp/issues
topics: [xmpp, im, network, socket]

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  connecta: ^1.0.1
  crypto: ^3.0.3
  dartz: ^0.10.1
  dnsolve: ^1.0.0
  logger: ^2.0.2+1
  memoize: ^3.0.0
  meta: ^1.11.0
  synchronized: ^3.1.0+1
  unorm_dart: ^0.3.0
  xml: ^6.5.0
  xpath_selector_xml_parser: ^3.0.1

dev_dependencies:
  convert: ^3.1.1
  lint: ^2.3.0
  test: ^1.21.0

platforms:
  android:
  ios:
  macos:
  windows:
