name: echo
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  lint: ^2.0.1
  logger: ^1.3.0
  meta: ^1.9.1
  xml: ^6.3.0
