name: echo
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.2 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  lint: ^2.1.2
  logger: ^1.3.0
  xml: ^6.3.0
