name: protocol
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  echotils:
    path: ../echotils/
  error:
    path: ../error/
  events_emitter: ^0.5.2
  lint: 2.1.2
  ltx:
    path: ../ltx/
  web_socket_channel: ^2.4.0

dev_dependencies:
  test: ^1.21.0
